workflows:
  ios-workflow:
    name: iOS Workflow

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Clean project
        script: |
          flutter clean
          flutter pub get

      - name: Fix CocoaPods
        script: |
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock
          pod repo update
          pod install
          cd ..

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app