workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable

    scripts:
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get

      - name: Build iOS Simulator
        script: |
          flutter build ios --simulator --debug

    artifacts:
      - build/ios/iphonesimulator/*.a