workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable

    scripts:
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get

      - name: Fix iOS build issue
        script: |
          cd ios
          pod deintegrate
          pod install
          cd ..

      - name: Build iOS
        script: |
          flutter build ios --release

    artifacts:
      - build/ios/iphoneos/*.app