// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4U5g-Pf7rlh8wAJlDZn7-VY8VFBMj1JY',
    appId: '1:537574602213:web:4ed5f04c01163931cf2b0c',
    messagingSenderId: '537574602213',
    projectId: 'royal-academy-6c411',
    authDomain: 'royal-academy-6c411.firebaseapp.com',
    storageBucket: 'royal-academy-6c411.firebasestorage.app',
    measurementId: 'G-1GC8V3S9V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGFI4fouqeoeUaMQsN5qfVkY5lGB9-7CY',
    appId: '1:537574602213:android:9f36b8061d84f7c7cf2b0c',
    messagingSenderId: '537574602213',
    projectId: 'royal-academy-6c411',
    storageBucket: 'royal-academy-6c411.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlRakWT87wju9f3Q72nqA0Sof3AkD9X64',
    appId: '1:537574602213:ios:0447f994cd5b37a6cf2b0c',
    messagingSenderId: '537574602213',
    projectId: 'royal-academy-6c411',
    storageBucket: 'royal-academy-6c411.firebasestorage.app',
    iosBundleId: 'com.royal.academy.royalAcademy',
  );

}